### ISSUE TITLE
No context to render liquid when a picture tag is used in a _layout file

### ISSUE THREAD

**Issue by bryanbergman** [rbuchberger/jekyll_picture_tag#11]
When I try to run Jekyll, I get `Liquid Exception: undefined method`[]' for nil:NilClass in post.html`

A traceback shows `/Users/Bryan/Desktop/sl/_plugins/picture_tag.rb:42:in`render': undefined method `[]' for nil:NilClass (NoMethodError)`

post.html is in my _layouts, I wonder if that is affecting it.

``html
{% include header.html %}

```
    {% picture articleimg {{ page.title }} alt="yep" %}

    <div class="wrapper">

        <article class="post">

            <header>
                <h1><a href="{{ page.url }}">{{ page.title }}</a></h1>
                <p><time datetime="{{ page.date | date: "%Y-%m-%d" }}">{{ page.date | date: "%B %d, %Y" }}</time></p>
                <p>By <a href="http://twitter.com/bryanbergman/" target="_blank">Bryan Bergman</a></p>
                <p>Reading time: <strong>{{ page.reading-time }}</strong></p>
            </header>

            {{ content }}

        </article>

        <div class="all"><a href="{{ site.url }}/archives">See all posts &rarr;</a></div>

    </div>
```

{% include footer.html %}

```
```

**Comment by anroots** [comment]
After installing the gem, I got `undefined method `[]' for nil:NilClass` error when compiling. Defining the `default` preset in `_config.yml` solved this.

Adding a more informative exception message ("Default preset configuration not defined") would be beneficial to new users.

**Comment by ChrisChinchilla** [comment]
I can confirm that @anroots suggestion worked for me to. Though I have another issue know, not sure if it's related…
