### ISSUE TITLE
Superfluous {::nomarkdown} tags

### ISSUE THREAD

**Issue by kslstn** [rbuchberger/jekyll_picture_tag#124]
The images in my layout includes now have `{::nomarkdown} {:/nomarkdown}` around them. That happened after updating Jekyll and its dependencies. 

What do you recommend to get rid of those tags?

Probably related to #107 and #28

**Comment by rbuchberger** [comment]
Do you mind sharing the markup where you get those extra tags? 

To stop them, add `nomarkdown: false` under `picture:` in your site `_config.yml`.

**Comment by kslstn** [comment]
Amazing, thank you, that solved it!

Here's one of the tags I'm using (the other one is very similar).
```
      {% picture header-logo-lazy
          /assets/img/site-logo.png
          --alt {{site.logo-description}}
        %}
```
Here's the template:
```
header-logo-lazy:
    markup: data_auto
    formats: [webp, original]
    widths: [38, 76, 115, 153, 306, 459]
    attributes:
      img: class="site-header__logo js-only lazy"
```

I tried changing the widths and removing the attributes, but that didn't make a change. I'm using this in an included html for my website's header. Below is the full include. I moved the tag to other places inside that template (outside the `<a> `tag, as a direct descendant of `<body>`, below, above and inside `<div class="page-container">`. All had the same issue for both tags.

```
<!DOCTYPE html>
<html lang="en" prefix="og: http://ogp.me/ns#" class="no-touch">
{%- include head.html -%}
<body class="body" ontouchstart="">
  <div class="page-container">
    <header class="site-header">
      <div class="site-header__nav-container">
        <nav class="site-header__nav">
          <a href="/" class="h5 site-header__nav-item">Home</a>
          <a href="/about" class="h5 site-header__nav-item">About</a>
          <a href="/now" class="h5 site-header__nav-item">Now</a>
        </nav>
        {%- include theme-selector.html -%}
      </div>
      <a class="site-header__logo-link" href="/">
        {% picture header-logo-lazy
          /assets/img/site-logo.png
          --alt {{site.logo-description}}
        %}
        <noscript>
          {% picture header-logo-noscript
            /assets/img/site-logo.png
            --alt {{site.logo-description}}
          %}
        </noscript>
      </a>
      <dl class="site-header__definition-list">
        <dt class="site-header__definition-term"><a href="/" class="h3 site-header__site-title">{{site.author}}</a></dt>
        <dd class="site-header__about-site">
          {%- assign about-short-size = page.about-short.size -%}
          {%- assign about-long-size = page.about-long.size -%}
          <span class="site-header__about-site-short">{%- if about-short-size > 2 -%}{{page.about-short}}{%- else -%}{{site.about-short}}{%- endif-%}</span><span class="site-header__about-site-long">{%- if about-long-size > 2 -%}{{page.about-long}}{%- else -%}{{site.about-long}}{%- endif-%}</span>
        </dd>
      </dl>
      <div class="site-header__contact">
        <h2 class="h4 site-header__title-contact">Contact</h2>
        {%- include contact-channels.html -%}
      </div>
    </header>
    <main role="main" class="main">
      {{ content }}
    </main>
  </div>
</body>
<script type="text/javascript" src="/assets/js/script.js"></script>
<script src="//instant.page/1.2.1" type="module" integrity="sha384-/IkE5iZAM/RxPto8B0nvKlMzIyCWtYocF01PbGGp1qElJuxv9J4whdWBRtzZltWn"></script>
</script>
</html>
```
For what it's worth, I tried using an old version as suggested in #28, like this:
`gem 'jekyll-picture-tag', git: 'https://github.com/robwierzbowski/jekyll-picture-tag/', tag: 'v1.2.0'`
However, that version seems to be incompatible with something in my setup as Jekyll wouldn't build at all.

**Comment by rbuchberger** [comment]
Hey! Thanks for closing it, but I'd like to keep it open though since it is an actual bug that I've been procrastinating on. The fix I gave you is just a workaround. Since you're using it in an HTML layout, it shouldn't include nomarkdown tags at all regardless of the setting.

**Comment by feliwir** [comment]
I think i am getting this bug aswell. When i use the picture tag from html i get `{::nomarkdown}` aswell

**Comment by rbuchberger** [comment]
Hey y'all, I couldn't fix this entirely but I did try to improve the auto-detection and added an override setting. I wrote up a [wiki page](https://github.com/rbuchberger/jekyll_picture_tag/wiki/Extra-%7B::nomarkdown%7D-tags-or-mangled-html%3F) that goes into more detail.
