### ISSUE TITLE
Problem with Github Pages and Jekyll

### ISSUE THREAD

**Issue by pkellner** [rbuchberger/jekyll_picture_tag#150]
Sorry for the newby question or problem here. Not a ruby or gem kind of guy.

I've got the responsive images working very well on my local with `jekyll serve` but when I copy to github page, I get this error inside.

```
 Your site is having problems building: The tag picture on line 16 in _posts/2019-09-07-integrating-jekyll-and-smartforms-with-recaptcha-free.md is not a recognized Liquid tag. For more information, see https://help.github.com/en/articles/page-build-failed-unknown-tag-error.
```

**Comment by rbuchberger** [comment]
GitHub pages only allows a very short list of plugins, which sadly doesn't include JPT. You'll either need to do without, or switch to another hosting provider. There are many good options; Netlify has worked well for me.

I should put that in the docs somewhere; I bet it trips up a lot of people. It's not a very helpful error message.

**Comment by pkellner** [comment]
Thanks.  I’d like to suggest to GitHub that add this.  Can you suggest the words? I don’t know exactly what to ask for. P

**Comment by rbuchberger** [comment]
I'll look into it. All you'd ask for is to add JPT as an optional GH-pages plugin, which you can read about [here](https://help.github.com/en/articles/configuring-jekyll-plugins). I understand they're deliberately keeping a very short list, and JPT makes the build process pretty heavy, so I'm not super hopeful. 

Seriously, Netlify is really easy. Just give it the GitHub repo and it clones & builds it automatically.

**Comment by pkellner** [comment]
I like that GitHub pages are free, super reliable and likely to be there forever. If netlify goes away, what would be the alternatives to switch to?

**Comment by pkellner** [comment]
Follow on.  I did try publishing what works on my local to netlify and I got an error, something about webp not found. I'm totally not a ruby gem guy and sadly don't even know where to start. I've kind of bumbled my way to get things working.  I'm starting to feel more and more like Jekyll really is not a great place unless you know the underlying tech, unlike wordpress, where you can really make a great blog without knowing anything about php. Totally get it's not a problem or issue here on this repo but thought I'd comment on that anyway.  

BTW, thank for taking the time to answer above. I really appreciate it

**Comment by rbuchberger** [comment]
That's weird, I have a couple sites that deploy to netlify and they work great. 'webp not found' is an imagemagick error, which is outside of ruby. Basically the Webp package isn't installed on whatever OS they're using to run the build process. 

I'm going to add a note to the documentation to clarify that GH-Pages doesn't suppport this plugin, because I think it trips up a lot of people. Sorry it didn't work out!
