### ISSUE TITLE
Add ability to pass arbitrary settings to imagemagick

### ISSUE THREAD

**Issue by alexandre1985** [rbuchberger/jekyll_picture_tag#160]
How can this plugin do:
```
magick file.png -quality 50 -define webp:lossless=true file.webp
```
??

**Comment by rbuchberger** [comment]
You can set image quality, which is documented here:

https://rbuchberger.github.io/jekyll_picture_tag/presets (ctrl+f quality)

There's no option to set lossless compression, though it wouldn't be hard to add a setting for it. I'll look at doing that, or maybe I'll add the ability  to pass arbitrary commands along to imagemagick.

**Comment by alexandre1985** [comment]
Either way, will be fine.
You have this [minimagick issue for lossless](https://github.com/minimagick/minimagick/issues/499) if you need some help
