### ISSUE TITLE
Slow compilation time

### ISSUE THREAD

**Issue by mutil** [rbuchberger/jekyll_picture_tag#161]
Thank you for this wonderful plugin, it is very useful.

The only problem is that I have a project with ~200 images and it takes around 60 seconds everytime to rebuild it. Is there any way that I can temporarily disable the plugin when I don’t work with images to speed up build time? If I remove it, then the `picture` tag is not found and compile fails.

I don’t know if this delay is due to searching the filesystem for new files or the generation of the tags. If it is the former, I think it would be easier to implement a global switch to disable searching for modified images.

Thank you once again.

**Comment by rbuchberger** [comment]
Currently there's no off switch, but "Do nothing sometimes" is likely within even my meager capabilities. 

During the build process, JPT builds an MD5 checksum of all the source images, in case of name collisions. This is probably what takes so long; generating the HTML is fast (though it does depend on said checksum, since it's part of the generated image names). 

The quick and dirty way to do this is add a "disabled" config setting, which can just leave a placeholder wherever an image tag would be. The harder way would be to search the generated images folder for images with the right base name and size, and assume they are correct, ignoring the checksum. This wouldn't protect you from accidentally using images with the same name, but it might be a nice feature to speed up build times.

I'll try to get the first one implemented quickly, to save you from your painfully long builds most of the time, and I think the second idea might be a great addition further on in the future to shave development build times.

Thanks for the feedback!

**Comment by rbuchberger** [comment]
That pull request will add the 'disabled' config setting I talked about. The new version will be up on rubygems within the next couple days; there are a few more issues I'd like to get in before pushing a new version.

I'd like to leave this issue open, because I really like the idea of a 'fast build' option which skips MD5 checking. Might take a little while to get to it though. 

Once you get the update, let me know what you think. Thanks!

**Comment by mutil** [comment]
Nice, works as expected, reducing dev build time by 90% or more. Big relief!

I have some remarks, though:
- The generated markup should be more neutral in my opinion. For example, if you have the pretty common markup: `<a ...>{% picture test.jpg %}</a>`, the generated div would be out of `<a>`, because it contains another anchor. It breaks the layout in unpredicted ways.
- Inline styles and no CSS class makes it difficult to style the placeholders.

Ideally, the markup should be as close to the one without the placeholder. Adding the rest attributes of the picture/img tag would also be beneficial. As for the image, I think replacing it with an empty SVG as data/image is feasible. I don’t find it crucial to be reminded that this is a placeholder, as the `disabled` option is not the default and I probably have already read the docs as to discover it.

I would consider something like the following markup:
```
<picture class=”JPT-placeholder {… rest PictureTag classes}”>
  <img src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'/%3E" />
</picture>
```

Keeping the original properties may requires getting deeper in the tag generation process but it can be useful for keeping the layout intact. As for the SVG, [in this post](https://codepen.io/tigt/post/optimizing-svgs-in-data-uris) you can read more about and explore alternative ways.

What do you think?

**Comment by rbuchberger** [comment]
You're right, I threw in the placeholder as an afterthought and and as you have tactfully pointed out it is pretty terrible. It would be nice to spit out a generic string for the placeholder as this solution does, but I don't think there's one that won't break someone's layout. JPT can return anything from a link to a single image, to an <img>, to a <picture>, so no matter what I choose it'll break something for someone.

I'll have a go at it tomorrow; I think generating all the same markup and simply replacing the images with empty SVGs is the best solution. I'll move the "disabled" check from the initial "generate html" step to the "generate images" step. It'll be a *touch* slower, but not by much.

I like your suggestion to add on a 'jpt-placeholder' class to the parent element as well, so people can color it or whatever they like. It's also dead-easy to do.

I really appreciate your help!

**Comment by rbuchberger** [comment]
Sorry I didn't get a new version out today, but I made good progress on the fast build solution which skips MD5 hashing most of the time. Unit tests are passing, but it needs some polishing and more testing before I can publish it. I believe it'll be nearly as fast as the disabled option, without having to bother with placeholders at all. I'll try to get something up tomorrow

**Comment by rbuchberger** [comment]
Pull request is up! I'd like your feedback before I merge it into master though. I tested it on a site with some 200 images:

* disabled: .16 s
* fast_build: 5.6s
* normal: 8.3s

So it's not the huge improvement I was hoping for, but it's not worthless either. Hopefully you'll see better results. Maybe I need to rewrite parts of this plugin in rust... I've always wanted to learn!

To test the fast_build option, set your gemfile to pull from this repo's `fastbuild` branch and set `fast_build: true` under `picture` in `_config.yml`. 

Regarding the placeholder, for now I think that when disabled, returning nothing at all makes the most sense. It'll be the fastest, least intrusive, and it will hopefully break the fewest things. I could add a second option to return empty SVGs, which will hopefully be faster than fast_build, while not dorking up your whole layout.

**Comment by mutil** [comment]
Hello. I tested the fastbuild branch and found it slightly faster (but not by a considerable amount). For 150 images and 7 generated widths, the normal build completes in 21-22 seconds while fast builds have an average of 20 seconds. Running with the disabled option is super fast.

About the placeholders, although an extra option about an empty SVG would be nice for some cases, I am pretty content with the current status of removing the tag entirely.

I just saw that you opened a new issue and more optimizations are coming. Keep up the good work, thank you!

**Comment by rbuchberger** [comment]
Bummer! I really thought that would help you out. Apparently there's some other bottleneck here.

It's totally cool if you aren't willing to go to the trouble, but if you're motivated you could help me see what exactly is taking so much time - install [rbspy](https://rbspy.github.io/) and profile it for me. Just run `rbspy record bundle exec jekyll build` and send me the flamegraph it produces. I have some ideas of where to optimize, but clearly my test builds on my machine don't cover all situations.

Honestly, until you brought it up I hadn't given much thought to optimizing performance. I wasn't aware that anyone was using JPT for anything that big, so I didn't worry about it!

**Comment by mutil** [comment]
No trouble at all, glad to help you.
Here is the flamegraph, tell me if you need something else.

[rbspy-2020-01-30-By2NrW6Qip.flamegraph.zip](https://github.com/rbuchberger/jekyll_picture_tag/files/4136200/rbspy-2020-01-30-By2NrW6Qip.flamegraph.zip)

**Comment by rbuchberger** [comment]
Thanks a ton, and sorry for a slow response!

It looks like fixing #165 will speed your build up at least some. I'm working through it now!

**Comment by rbuchberger** [comment]
Ok, new changes are up on the `fastbuild` branch. Took my 5.5 second test build down to .4 seconds! For builds where no new images are needed, I've eliminated all disk IO except for checking file existence. 

Do you mind giving it another shot? And if it's still slow, could you run another profile? Thanks!

**Comment by mutil** [comment]
Wow, impressive! From over 25 seconds down to ~6.5 seconds.
Very nice, thank you!

**Comment by rbuchberger** [comment]
Outstanding! That's what I wanted to hear.

I'll go ahead and close this issue, but I'll keep working on build times. If it ever gets worse again, let me know.
