### ISSUE TITLE
data_auto, data_img, data_picture src="" missing

### ISSUE THREAD

**Issue by alexandre1985** [rbuchberger/jekyll_picture_tag#166]
For correct markup, I believe the `markup: data_auto` should add the `data-src`, instead of replacing the `src` with a `data-src`.
This way would generate correct image markup, with the attributes `src` and `data-src`.
Correct?

**Comment by alexandre1985** [comment]
I tested and saw that with an `src` attribute the image lazyloading (which is what I want to achieve) does not proceed correctly.
So it is fine as it is for me.
As a matter of clarity, `data_auto` should be renamed to something related to lazyloading, because replacing `src` with `data-src` is what we want to do in lazyloading; else `data_auto` should append `data-src`.

**Comment by rbuchberger** [comment]
I'm not sure I understand your use case here. What are you trying to accomplish? 

If we return a `src` attribute alongside a `data-src` attribute, the browser will ignore the `data-src` and immediately start downloading the `src` as it parses the page, before any JavaScript has a chance to do anything. (The same is true for `srcset`/`data-srcset`). If you want to show a different image with JS, it will have to download that second image, meaning you'll download 2 different files for the same image. Is there some scenario where this is desired behavior?

Regarding setting names, that ship has sailed. I am super reluctant to make any breaking changes. I'll add new capability all day long, but I'm not causing headaches for our users by renaming settings unless I absolutely have to.

**Comment by alexandre1985** [comment]
> If we return a src attribute alongside a data-src attribute, the browser will ignore the data-src and immediately start downloading the src as it parses the page, before any JavaScript has a chance to do anything. (The same is true for srcset/data-srcset). 

Yes, for image lazy loading `src` must not be present

> If you want to show a different image with JS, it will have to download that second image, meaning you'll download 2 different files for the same image. Is there any scenario where this is desired behavior?

I don't. I was doing image lazy loading only.

> Regarding setting names, that ship has sailed. I am super reluctant to make any breaking changes. I'll add new capability all day long, but I'm not causing headaches for our users by renaming settings unless I absolutely have to.

Makes total sense.

Thank you @rbuchberger :smiley:
