### ISSUE TITLE
Feedback wanted: Should we change the way generated images are named?

### ISSUE THREAD

**Issue by rbuchberger** [rbuchberger/jekyll_picture_tag#168]
Currently, generated images are given mostly human readable filenames based on the source image name, a truncated hash of the source image, and the generated image width. For example: `some_folder/myimage.jpg` becomes something like `_site/generated/some_folder/myimage-abc123-800.jpg`

I'm considering whether they need to be human readable at all. I could come up with some deterministic, hash-based, encoded form of relevant, quickly available metadata (including the things above) and use that for filenames. For example: `some_folder/myimage.jpg` might become `_/site/generated/abcd1234.jpg`

Advantages:

- I can encode more information in the filename, reducing dependence on hashing the source image (which is slow) to identify images, without creating overly long filenames. With this change, I would feel comfortable enabling `fast_build` (which skips hashing source images when a likely correct generated image already exists) by default, giving everyone faster build times. 

- Filenames can be a bit shorter, which could save a little bandwidth.

Disadvantages:

- Generated image filenames will turn into basically random character strings. Reading your generated site's HTML will be harder.

- On the first build after the update, every image will need to be rebuilt. You'll want to clear out the generated images folder as well, as the old images will no longer be used. 

It's not an urgent change, but if anyone has thoughts I'd love to hear them. Good idea? Not worth the trouble? 

Edit: added examples

**Comment by ftruzzi** [comment]
I think having random filenames would be very nice, for consistency at least. Personally, I don't like having original filenames in my `assets` folder and was already thinking of randomizing them with hash strings. If that also brings faster build times, then I'm all for it!

I think the image width should continue to be explicit in the filename though. What about `hash-width.ext`? And what about also renaming the original file to `hash.ext`?

Yes, hashes are hard to read but not necessarily harder to identify: looking for `2fa3ee2` in a folder full of random hashes is easier than finding `DSC_9997` in a folder full of `DSC_99**` 😄

**Comment by rbuchberger** [comment]
I hadn't thought about that! I don't think I want to rename the original files; in my mind those are not something the plugin should be messing with, beyond reading them. 

You're right that the width should still be a human-readable part of the filename, that way it's clear when reading the output markup that things are working like you expect. Do you spend a lot of time digging through the generated `_site` directory?

**Comment by ftruzzi** [comment]
>  I don't think I want to rename the original files; in my mind those are not something the plugin should be messing with, beyond reading them.

Makes sense, but then would one be able to identify the original image by looking at the filename of a generated one?

> Do you spend a lot of time digging through the generated _site directory?

Right now yes, but I'm in the process of moving my website from Wordpress to Jekyll... hopefully that will change later :D

**Comment by rbuchberger** [comment]
> Makes sense, but then would one be able to identify the original image by looking at the filename of a generated one?

No, that's why I'm not sure about the change.

> Right now yes, but I'm in the process of moving my website from Wordpress to Jekyll... hopefully that will change later :D

Makes sense! That use case hadn't occurred to me.

**Comment by kslstn** [comment]
For my applications it doesn’t matter much. However, for debugging responsive behavior, it’s useful to have the image size in the file name. With that you can immediately see whether the correct file is downloaded or not.

**Comment by rbuchberger** [comment]
There's a third possibility I hadn't thought of - use some cache file to persist data between site builds. Then we don't have to use the filename for that purpose, and it can go back to just identifying files as god intended. I'd probably put the cache file in the generated images folder by default (so it's automatically gitignored), with an option to change it if people don't want that file in their built site.

I'm not sure if Jekyll builds tags in parallel; if so we'll need to account for that.

**Comment by stuntbox** [comment]
+1 for maintaining human-readable filenames in the final output. As @kslstn notes, I have definitely used this for debugging purposes many times. If the speed improvements on build time could be achieved with the interim cache file instead, 👍.
