### ISSUE TITLE
srcset not working

### ISSUE THREAD

**Issue by velasco** [rbuchberger/jekyll_picture_tag#188]
Hi, I installed the gem and the assets are being built properly. But when I reduce the browser window, the browser does not access the smaller assets, only the 1000px version. Why is that?

**Comment by rbuchberger** [comment]
Sorry you're having trouble!

Chrome won't download smaller images if you resize down (Firefox will, however). Try starting with a narrow window and enlarging it.

**Comment by velasco** [comment]
No trouble, I was just curious. Thank you for your quick reply. Regards, Francisco
