### ISSUE TITLE
Feature: Add built-in presets & media queries.

### ISSUE THREAD

**Issue by rbuchberger** [rbuchberger/jekyll_picture_tag#189]
1. Allow presets to inherit settings from each other. Will save time and repetition when writing them. Use some setting like `inherit: (preset name)`
2. Create more built-in presets. For example, we could create one named `jpt-webp` which is exactly like the default, except it also generates webp images. You could inherit from the built-in preset for small tweaks, or just use it directly in a liquid tag. 

This would technically require a major version change, because I'd have to cordon off a preset namespace. (Probably the `jpt-` prefix). The benefit is that getting started will be even easier; many users won't have to write presets at all.

I could use help writing good default presets. Off the top of my head, some good candidates would be:
- webp
- width and height attributes
- lazy loading
- direct url

**Comment by stuntbox** [comment]
@rbuchberger FWIW, those four you listed were the first ones that came to mind for me too.

**Comment by rbuchberger** [comment]
Thanks! The cool thing is once I make the feature, adding new ones is super simple, so hopefully we'll get some suggestions and pull requests.

**Comment by rbuchberger** [comment]
Update: I've decided that adding inheritance isn't a great idea. JPT's configuration is simple enough that it will likely add more confusion than it removes; sure you'd have less repetition, but it would be much less clear what a given preset actually does. 

We'll still add stock presets and media queries, and publish them in the docs as a configuration starting point.
