### ISSUE TITLE
disable generating in development, use src instead

### ISSUE THREAD

**Issue by silveltman** [rbuchberger/jekyll_picture_tag#194]
I know I can disable for development with 'disabled: development' in config, but this prevents any img of up showing at all. 

Is there a way of disabling the generations but use the src img instead? This way we don't have to wait for generation in development while still being able to see the img and apply the css. Also, this way we dont have to store all the generated imgs in our local environment, which can take up a lot of storage space. 

If this is not yet possible, I would love to see this as a feature <3

**Comment by rbuchberger** [comment]
I'll have to think on this a bit. My concern is that properly generated images can be cropped, and can have completely different output markup. This might lead to your dev builds looking completely different from your production builds. 

I can see the advantage if you're working with huge sites on limited hardware, and a big warning in the docs would keep people aware of the pitfalls.

**Comment by rbuchberger** [comment]
Hey, I'm sorry but I've decided I'm not going to do this. The benefits aren't worth the cost in added complexity and code. I only have so much time to put into this project, and this would require a good amount of work and has a lot of potential to introduce new bugs.

I'm going to close this feature request for now; if anyone in the future wants to take a crack at adding this feature please feel free to reopen it.
