### ISSUE TITLE
Images keep being regenerated on every build

### ISSUE THREAD

**Issue by raulcraveiro** [rbuchberger/jekyll_picture_tag#197]
I'm using the plugin with Netlify, but in every build they keep regenerating the images.

If you wanna take a look, this is the repository: https://github.com/raulcraveiro/jekyll-craveiro

**Comment by rbuchberger** [comment]
Hello! The reason for this is netlify doesn't re-use build environments. It spins up a fresh container for every build, which won't have any fresh images. There might be a way to configure netlify to cache certain directories, but I'm not aware of it.

**Comment by raulcraveiro** [comment]
Do you know if Vercel do that? 🤔
