### ISSUE TITLE
Use in frontmatter ?

### ISSUE THREAD

**Issue by ImaCrea** [rbuchberger/jekyll_picture_tag#201]
Hi there,
I'm trying to use a generated image in "image:" in my frontmatter. It's the thumbnail jekyll seo is pulling for opengraph.

But it doesn't seem I can use liquid in frontmatter. Do you know a walkthrough please?

Otherwise, I might have to modify Jekyll SEO plugin?

**Comment by ImaCrea** [comment]
Any idea @rbuchberger please?

**Comment by rbuchberger** [comment]
Hey, I'm sorry I never answered this. I don't know of a way to use a liquid template tag in frontmatter; maybe you can use an include of some kind? If you haven't found a solution already.

**Comment by hanniabu** [comment]
@ImaCrea check out the [liquify plugin](https://github.com/vividh/liquify), it allows you to use liquid in frontmatter.

**Comment by rbuchberger** [comment]
I'm going to close this since it's out of the scope of JPT. Sorry I couldn't be more helpful, and @hanniabu thanks for the advice!
