### ISSUE TITLE
[Feature] Respect --disable-disk-cache and disable_disk_cache

### ISSUE THREAD

**Issue by jbdaley** [rbuchberger/jekyll_picture_tag#212]
I'm attempting to prevent all writes to my source tree during Jekyll builds. jekyll_picture_tag is not respecting the [disable-disk-cache flag](https://jekyllrb.com/docs/configuration/options/). This flag was added in Jekyll 4.1.0.

```
agent_1  | [Container] 2020/12/15 08:36:19 Running command bundle exec jekyll build --disable-disk-cache --trace
...
agent_1  |   Liquid Exception: Permission denied @ dir_s_mkdir - ...
agent_1  | bundler: failed to load command: jekyll (/usr/gem/bin/jekyll)
agent_1  | Errno::EACCES: Permission denied @ dir_s_mkdir - /codebuild/output/srcDownload/src/.jekyll-cache
agent_1  |   /usr/local/lib/ruby/2.7.0/fileutils.rb:250:in `mkdir'
agent_1  |   /usr/local/lib/ruby/2.7.0/fileutils.rb:250:in `fu_mkdir'
agent_1  |   /usr/local/lib/ruby/2.7.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
agent_1  |   /usr/local/lib/ruby/2.7.0/fileutils.rb:226:in `reverse_each'
agent_1  |   /usr/local/lib/ruby/2.7.0/fileutils.rb:226:in `block in mkdir_p'
agent_1  |   /usr/local/lib/ruby/2.7.0/fileutils.rb:211:in `each'
agent_1  |   /usr/local/lib/ruby/2.7.0/fileutils.rb:211:in `mkdir_p'
agent_1  |   /usr/gem/gems/jekyll_picture_tag-1.13.0/lib/jekyll_picture_tag/cache/base.rb:23:in `write'
agent_1  |   /usr/gem/gems/jekyll_picture_tag-1.13.0/lib/jekyll_picture_tag/images/source_image.rb:81:in `update_cache'
```

The expected behavior would be that jekyll_picture_tag falls back to an non-caching implementation or fails with an error when either are these configurations are set. The cache_dir configuration [is already being supported](https://github.com/rbuchberger/jekyll_picture_tag/blob/master/lib/jekyll_picture_tag/cache/base.rb#L43).

**Comment by rbuchberger** [comment]
I need to do some work on the caching implementation anyway, because Jekyll 3 doesn't support it either (per #192). 

Thanks for the feature request! I'll put some time into it.

**Comment by rbuchberger** [comment]
Done! Look for it in the next release.
