### ISSUE TITLE
Move from imagemagick to libvips

### ISSUE THREAD

**Issue by rbuchberger** [rbuchberger/jekyll_picture_tag#226]
There have been suggestions to replace ImageMagick as the image generator with libvips, via the ruby-vips gem. 

Benefits:
* Markedly faster builds
* simpler installation; Unlike ImageMagick it appears that all the major package managers ship a relatively recent version of libvips.
* Possibly some new features, such as smart cropping which attempts to keep the most interesting part of the image. 

Drawbacks:
* Will likely require changes to the crop & gravity syntax, both in the preset and in liquid tags. We'd keep simple aspect ratio cropping the same, but anything more complicated than that would likely change. This would naturally require a major version bump. 
* Development time required.

**Comment by rbuchberger** [comment]
Note: Once we write the feature, we should work out what the oldest version of libvips we can use is. Since the changelog is huge, I think the easiest way is to write a script that runs the test against different versions until something breaks.

**Comment by rbuchberger** [comment]
Update: This is mostly finished. All that's left is creating the smartcrop 'interestingness' setting, and updating the documentation. The v2 test branch is failing because I'm having trouble with getting github's CI to handle jp2 and avif images. (I'm not very smart on ubuntu)

The build time difference is significant; with my particular site on my particular computer, the build time is 261 seconds on the current master branch and 57 seconds on the v2 branch.

**Comment by jordikitto** [comment]
Awesome! Can't wait. Any idea when this will be live? :D

**Comment by rbuchberger** [comment]
Couple weeks maybe? I had wanted to cram a bunch of changes into the v2 release, but now I'm thinking I'll pare it down to just the breaking changes and leave the non-breaking new features for later. It's taking too long.

Since it's such a big set of changes I'd like to do a pre-release version, and it'd be awesome to get some help testing it. Just make sure it works with both your local build and deployment process. Will update when that becomes available.

**Comment by rbuchberger** [comment]
Update: I'd consider the v2 branch to be in a usable (for testing) state now. If y'all want to pull it and try, go ahead! I'd love feedback.

Documentation is still in progress, but there's a migration guide under notes in the docs folder.

**Comment by jordikitto** [comment]
Managed to get it working and... **it's so much faster!!**

Awesome work! Love it. We have tons of images building and managing them has always been a huge issue. Used to take an hour 1 generate and now it's like 5 mins!

We have a pretty simple setup, just generating webp and png images at various sizes, so wasn't difficult to migrate :)

**Comment by rbuchberger** [comment]
Warms my heart to hear that :) 

Thanks for checking! I'll try to get a pre-release out as soon as I can. Please report back if you run into any issues, a whole lot of code changed so it could still happen.

**Comment by jordikitto** [comment]
Hey, so far so good on my machine but on almost all other machines I keep getting this error
```
 Liquid Exception: VipsForeignLoad: "/Users/jordi/path/to/file/60a9aa00-cfa9-11e9-b4fe-6d6f75736579.png" is not a known file format in /Users/jordi/path/to/file/class-naming-conventions.md
```
I've been at it for days trying to figure it out, any ideas?

**Comment by rbuchberger** [comment]
Has to do with the vips installation, apparently on those machines it doesn't know how to read PNG files. I'll have to do some learning.
