### ISSUE TITLE
How to correctly handle portrait images?

### ISSUE THREAD

**Issue by IanCassTwo** [rbuchberger/jekyll_picture_tag#231]
Hi,

Do you have any advice on how to correctly handle portrait images when mixed on a page with landscape? Ideally, I'd like the portrait images to be narrower than the landscape so that the height is the same. However, what I'm finding is that the widths are always the same which means that the portrait images are much higher.

Here's what I'd like to achieve
![image](https://user-images.githubusercontent.com/30568591/104459118-3a893480-55a4-11eb-992c-9fed7a834743.png)

This is what I get with JPT
![image](https://user-images.githubusercontent.com/30568591/104459162-4bd24100-55a4-11eb-8504-d2c5e370f5c7.png)

Thanks

**Comment by rbuchberger** [comment]
By closing it, I assume you figured it out? I think this is a problem that CSS flexbox can solve.

**Comment by IanCassTwo** [comment]
Yeh. I realized this wasn't a JPT issue and was something I could solve by
simply learning more. Flexbox was one of the solutions I read about.
