### ISSUE TITLE
AVIF

### ISSUE THREAD

**Issue by IanCassTwo** [rbuchberger/jekyll_picture_tag#234]
Any plans to add support for AVIF?

**Comment by rbuchberger** [comment]
Yes! Your timing is perfect; yesterday I created [this issue](https://github.com/mime-types/mime-types-data/issues/38#issuecomment-778422002) with one of the showstoppers, and they've already pushed an update.

Assuming your installation of ImageMagick also supports AVIF, I believe that if you run `bundle update` it should start working. Let me know?

**Comment by rbuchberger** [comment]
Update: it looks like the method we use to get a  MIME type for a given file extension doesn't work with AVIF yet. Not sure if this is an upstream bug, but I can work around that if necessary.

**Comment by IanCassTwo** [comment]
I added "avif" to the formats array & everything seems to work as expected :)

**Comment by IanCassTwo** [comment]
ah, except it doesn't create avif for png source files

**Comment by rbuchberger** [comment]
Huh... failing to convert png -> avif is imagemagick's fault, but JPT shouldn't just act like everything worked fine. I'll play with it a bit.

**Comment by IanCassTwo** [comment]
I found the cause, and it was some missing images due to an error in a script. I don't think there's an issue with JPT after all

**Comment by halostatue** [comment]
> Update: it looks like the method we use to get a MIME type for a given file extension doesn't work with AVIF yet. Not sure if this is an upstream bug, but I can work around that if necessary.

The IANA MIME types registry doesn’t typically include extensions. You’re more than welcome to submit a PR that will add appropriate extensions for AVIF detection by filename (the modification would be in the `types/images.yaml` file).

**Comment by rbuchberger** [comment]
@halostatue - thanks, I'll do that! Expect a PR in the next week or so.

@IanCassTwo - glad to hear it's working but I'm actually a bit surprised that it does. Do the `source` tags for the avif files have a `media="image/avif"` attribute? I suspect they don't, which may or may not still work (web browsers can be cool like that), but it isn't correct.

**Comment by IanCassTwo** [comment]
No, you're right, they don't. However, it seems to work ok. I'm using it here if you want to take a look https://rlw7w.uk/

**Comment by IanCassTwo** [comment]
This looks like it's working now with the new mime-types-data :)

**Comment by rbuchberger** [comment]
Outstanding :) I'll close this then. Thanks to everyone involved!
