### ISSUE TITLE
Issue with zoom.js plugin

### ISSUE THREAD

**Issue by inakijv** [rbuchberger/jekyll_picture_tag#236]
Hi!
I am using zoom.js and after implementing JPT and when zooming in an image, the image enlarges less than expected (adding a short clip comparing current situation -not pushed yet- and also the behavior without JPT which takes almost full-screen width & height) https://recordit.co/GGvBBv0pp9

Any suggestions on what this issue might be? (or related issue/solution I could lookup);
Any suggestions on how to combine JPT & zoom effect plugins?

**Comment by rbuchberger** [comment]
Is it [this](https://github.com/fat/zoom.js) zoom.js? I'm not gonna dive into their source code, but the readme only mentions the src attribute, not srcset. My guess is it goes directly to the fallback image? 

Try setting [fallback_width](https://rbuchberger.github.io/jekyll_picture_tag/users/presets/fallback_image.html) to something bigger.

**Comment by inakijv** [comment]
Yes, it is that one.

Based on your suggestions, to make it work I set up the new `fallback_width` to the biggest size in my image presets and also changed the attribute `src` to `srcset` in the zoom.js file. That way I can get a pretty decent zoom effect.

**Comment by rbuchberger** [comment]
Glad to hear it's working! That's a neat little plugin, I might try it on my own site.

Let me know if you have any more trouble.
