### ISSUE TITLE
Issues running on Netlify

### ISSUE THREAD

**Issue by ChrisChinchilla** [rbuchberger/jekyll_picture_tag#242]
Hey, thanks for the plugin.

I have been using the older version for some time and thought I would try upgrading to V2. Everything runs perfectly locally, but when I push to Netlify, the build fails with this error…

`12:27:24 PM:   Liquid Exception: VipsOperation: class "magicksave" not found in {file path}`

As far as I can tell, this seems to be only related to PNG images, and I can confirm that the Netlify build image is missing libpng, but at the same time, this looks like a fallback to using imagemagick, which has always worked on Netlify. this is possibly also related to ruby-vips, but I am not really sure where to start…

**Comment by rbuchberger** [comment]
Yeah, I'm having exactly the same issue with a couple of sites. Another user has opened a thread on [netlify's help forums](https://answers.netlify.com/t/deploy-failed-exit-code-1-ci-jekyll-build-build-script-returned-non-zero-exit-code-2/34830/4); hopefully we can get them to add a few packages to their build images. 

I'm not exactly hopeful they will do that, though. At this point I'm thinking I'll add imagemagick as a backend, and allow people to switch between them.

I'm planning to make a section in the docs about deploying sites with JPT, because it's surprisingly tricky. I've moved over to an AWS s3 bucket and while the setup is a bit painful, once done it works really well.

**Comment by ChrisChinchilla** [comment]
@rbuchberger Ah ha, I also posted on another thread about the same issue, so we shall see… For now I downgraded… Thanks!

**Comment by ChrisChinchilla** [comment]
Could be useful actually… https://answers.netlify.com/t/unable-to-use-libpng-dependency/27109/2

**Comment by ChrisChinchilla** [comment]
Though that didn't seem to fix the issue, same error :(

**Comment by rbuchberger** [comment]
Success! There's a fix in version 2.0.2 - update to that and do your normal build. (`bundle update`, commit Gemfile.lock and push). No homebrew packages necessary. 

I haven't checked with jp2 and avif files, but jpg, png, and webp are working now, at least for my builds. Let me know if yours work too.

**Comment by YJPL** [comment]
> Success! There's a fix in version 2.0.2 - update to that and do your normal build.

Well done, thank you so much!

**Comment by rbuchberger** [comment]
After some testing, I've determined that avif and jp2 are a no-go (unless someone else can figure out a way to get them working; I couldn't). Webp, jpg, png, and gif are fair game. I've added some guidance to the docs on the subject. 

I'm not going to bother with reimplementing the imagemagick backend. This approach does everything imagemagick can do, but better.

**Comment by ChrisChinchilla** [comment]
It still broke for animated gifs, but I think that's an edge case, and frankly I had 3 amongst several hundred pictures, and was happy to just remove them :)

**Comment by rbuchberger** [comment]
You could just use plain markdown syntax for those. `[alt text](mygif.gif)`, which will give you a plain `<img src="mygif.gif" alt="alt text">`

Glad to hear it's working ;) I was stressing about this! Speed improvements are pretty useless if nobody can deploy...

**Comment by ChrisChinchilla** [comment]
They are all in front matter fields unfortunately, but really, it's not a big deal anyway ;)

**Comment by YJPL** [comment]
Netlify's deploy time for [@alternatyves](https://alternatyves.com) went from 9m 58s to 2m 18s with this update. Gifs still work (using Markdown syntax though).

Good work! Thank you again.

**Comment by rbuchberger** [comment]
Warms my heart to hear that! No promises, but It might get even faster in the next couple updates. The libvips maintainer was kind enough to look over the plugin and offer some advice.

I'm going to close the issue now, but if anyone has trouble in the future feel free to re-open it.
