### ISSUE TITLE
Avif generates Liquid Exception: stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by scalastic** [rbuchberger/jekyll_picture_tag#249]
Hi,

I encounter this odd error when trying to generate Avif picture with `jekyll_picture_tag` plugin on Github Actions using [helaili/jekyll-action](https://github.com/helaili/jekyll-action) :
```Liquid Exception: stack level too deep (SystemStackError)```

- On local dev, using `bundle exec jekyll serve` everything runs fine.
- On Github Actions, it's when I activate the Avif picture format generation that the error occurs, not with WebP for example.

I made a complete test case to reproduce locally the problem and with all details: <https://github.com/scalastic/jekyll-test-cases>

By the way, that could change your deployment on GitHub Pages: https://rbuchberger.github.io/jekyll_picture_tag/users/deployment.html#github-pages

Thanks!

**Comment by scalastic** [comment]
Linked issue: helaili/jekyll-action/issues/93

**Comment by rbuchberger** [comment]
Thanks for the bug report! I'm especially thankful for the test build that repoduces the problem; that's a lot more effort than most go to and I really appreciate it! 

I'm not sure what is causing this, so I'll need to spend some time digging. I'm a bit swamped with life right now so I can't promise I'll get to it soon, but I'll try to start as soon as I have a few free hours.

**Comment by scalastic** [comment]
Finally found a new and **working** GitHub Actions that uses `ArchLinux` distribution which contains a complete `libvips` (AVIF, WebP, JPEG,...). You can find it at https://github.com/jeffreytse/jekyll-deploy-action !

I used it on my own Jekyll site and it works great.

**Comment by rbuchberger** [comment]
That's super helpful! I'd love to switch to this and suggest others do too
