### ISSUE TITLE
Vips not found in Jekyll Docker image

### ISSUE THREAD

**Issue by typhoon2099** [rbuchberger/jekyll_picture_tag#251]
I'm using the Jekyll Docker image for local development, but I can't get Vips working. It's included in the image, but the command fails, which results in Jekyll Picture Tag failing:
```
jekyll_1   |   Liquid Exception: No such file or directory - vips in /srv/jekyll/jekyll/_layouts/post.html
jekyll_1   |                     ------------------------------------------------
jekyll_1   |       Jekyll 4.2.0   Please append `--trace` to the `serve` command 
jekyll_1   |                      for any additional information or backtrace. 
jekyll_1   |                     ------------------------------------------------
jekyll_1   | /usr/gem/gems/jekyll_picture_tag-2.0.3/lib/jekyll_picture_tag/parsers/image_backend.rb:17:in ``': No such file or directory - vips (Errno::ENOENT)
```
I'm not sure how to progress at this point, I can't upgrade jekyll_picture_tag because of this, and I don't know why the command is missing (Jekyll uses Alpine as a base if that helps).

**Comment by rbuchberger** [comment]
I'll try and troubleshoot it when I can, but I'm super swamped with life right now. I'd love to get a good working docker image set up for exactly this reason.

Thanks for bringing it up!

**Comment by scalastic** [comment]
@typhoon2099

At least, 2 packages are missing : imagemagick and vips-tools. 
Dev versions of both ones are installed with the original script from https://github.com/envygeeks/jekyll-docker but don't know what for.
I've built one adding these 2 packages (https://github.com/scalastic/jekyll-docker) BUT no Avif format is supported 😢.

You can test your build by running it in your Jekyll directory with (or build your image):
```
export JEKYLL_VERSION=latest
docker run --rm \
  --volume="$PWD:/srv/jekyll" \
  -it jeanjerome/builder:$JEKYLL_VERSION \
  jekyll build
```

**Comment by rbuchberger** [comment]
Awesome work! Maybe [libavif](https://pkgs.alpinelinux.org/package/edge/community/x86_64/vips-lang) will add avif support?

**Comment by scalastic** [comment]
I added libavif package. As it's only existing on Alpine Linux 3.13, I had to upgrade jekyll-docker reference image from ruby:2.7.3-alpine3.11 to ruby:2.7.3-alpine3.13.

Unfortunately I got this error when dealing with the first Avif image:
```
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux-musl]
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Generating new image file: /assets/img/jvm-execution-970-ec245f5f4.avif
/usr/gem/gems/ruby-vips-2.0.17/lib/vips/operation.rb:187: [BUG] Segmentation fault at 0x00007fb22f50e260
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux-musl]
```

It reminds me of something: https://github.com/rbuchberger/jekyll_picture_tag/issues/249 ☹️

I think Alpine Linux is the cause but I failed to install vips and imagemagick on Fedora or Debian... That's sucks!

**Comment by lsli8888** [comment]
Was anyone able to find a solution to fix this issue?

**Comment by typhoon2099** [comment]
Yes, building a custom image:
```
FROM jekyll/jekyll:4.2.0

RUN apk --no-cache add vips-tools
```

**Comment by lsli8888** [comment]
Thanks @typhoon2099.  Actually, I was able to do this on my own machine and on GitHub Pages - successfully.  Unfortunately, I'm trying to do the build on Netlify (which I'm trying to move to) and I don't have access to execute apk (or apt)...  So I'm sort of stuck on Netlify without being able to do a build on Netlify.  I guess a hack would possibly be to do the build on GitHub using GitHub actions and then use the Netlify CLI (perhaps using GitHub Actions for Netlify CLI to do this) to deploy the site after being built on GitHub.

**Comment by typhoon2099** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}                                                                                                                                               Sent via BlackBerry Hub+ Inbox for Android                                                                                                                                                                           From: ***@***.***: 20 September 2021 17:49To: ***@***.*** to: ***@***.***: ***@***.***; ***@***.***: Re: [rbuchberger/jekyll_picture_tag] Vips not found in Jekyll Docker image (#251)  
Which image are you using? I'm using Xenial 16.04 and it seems to work well.

**Comment by lsli8888** [comment]
@typhoon2099 I'm using the default build image in Netlify.  I believe it's Ubuntu 20.04 as I have the following image tag (https://github.com/netlify/build-image)
```
4:34:17 PM: build-image tag: v4.3.1
```
And yep, I don't have any issues on my own computer which is running Ubuntu 18.04

**Comment by typhoon2099** [comment]
Ah, I may have had trouble jumping up to 20.04 so I've stuck with 16.04 while it's not end of life.

**Comment by SebouChu** [comment]
Hello everyone! A few days ago, I added the CLI tools of Vips in Netlify's Focal 20.04 build image so you can now use Vips with the latest build image without any issue!
