### ISSUE TITLE
Duplicate folder in the path

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [rbuchberger/jekyll_picture_tag#258]
I am using `jekyll-multiple-languages-plugin` so I set `baseurl_key: baseurl_root`, and playing with `source: images` or without setting it, I can't get it working.

When I set `source: images`, the path has the images folder duplicated (i.e. https://example.com/images/images/hello.jpg) If I don't set it, the folder is missing (i.e. https://example.com/hello.jpg). Meanwhile, the image is working correctly, but the terminal has a lot of warnings (I need to use `ignore_missing_images: true` to run the site).

Why I can't get just an `images` folder (i.e. https://example.com/images/hello.jpg)?

**Comment by JavierSegoviaCordoba** [comment]
I was keeping the old `img`, commented, but for some reason, it was affecting 🤷‍♂️

**Comment by rbuchberger** [comment]
That is really weird! I'm glad you got it fixed, though. Don't be afraid to come back if you have any more troubles.
