### ISSUE TITLE
Documentation should consistently use presets

### ISSUE THREAD

**Issue by m8mble** [rbuchberger/jekyll_picture_tag#287]
I've been debugging an issue after upgrading from a 1.x version. In the end, it turned out to be caused by using `markup_presets` instead of `presets` in `_data/picture.yml`. This parameter rename has been clearly documented in the change notes.

In contrast, some places in the documentation still mention the old (removed) parameter name, e.g. [fragments](http://rbuchberger.github.io/jekyll_picture_tag/users/presets/markup_formats/fragments.html).

**Comment by rbuchberger** [comment]
Closing as associated PR is merged
