### ISSUE TITLE
Trouble using newer versions with jekyll-multiple-languages-plugin

### ISSUE THREAD

**Issue by kwisatz** [rbuchberger/jekyll_picture_tag#294]
I will keep on investigating, but posting this here nonetheless to see if someone might already have figured this out.
In the older releases (`jekyll 3.x`) I successfully used this plugin together with the [jekyll-multiple-languages-plugin](https://github.com/kurtsson/jekyll-multiple-languages-plugin).

I have added `img` to be excluded from localization, meaning that I get a single `_site/img` directory with all my resized images.
However, when constructing the `src` property for the `img` element, URIs are always relative to the current language tag, resulting in URIs such as `/de/img/blog/bildDE-600-76046ca47.png` for the German version of my site.

Not excluding `img` will not help since all the `multiple-languages-plugin` does is to copy files from their origin, not copy the files that have resulted from the `picture_tag` plugin's resizing.

**Comment by kwisatz** [comment]
Ok, got it, the `ignore_baseurl` parameter controls this.
And it's actually documented [here](https://github.com/rbuchberger/jekyll_picture_tag/blob/master/docs/users/configuration/urls.md)

**Comment by rbuchberger** [comment]
Glad you worked it out! There's also a documentation site that's a little easier to read - https://rbuchberger.github.io/jekyll_picture_tag/users/configuration/urls.html
