### ISSUE TITLE
JPG Quality Setting?

### ISSUE THREAD

**Issue by patrickcate** [rbuchberger/jekyll_picture_tag#32]
I don't know if I'm missing something, but is there an option to set the JPG quality of the generated files?

**Comment by thawn** [comment]
What are the currently used quality settings for jpeg images?

**Comment by ChrisChinchilla** [comment]
Seconded.

@robwierzbowski I would be happy to help with this as I need better quality for a project I'm working on. If you could point me in the direction of where you set quality I will attempt to add the functionality.

**Comment by btobolaski** [comment]
One problem is that we don't actually set it. These are the only options that we pass to imagemagick https://github.com/robwierzbowski/jekyll-picture-tag/blob/ae4307b193a2c48d445a08ca0b9fd472a7060c4f/lib/jekyll-picture-tag.rb#L240-L244

**Comment by jsanne** [comment]
Hi all,
I found the follwing information:
https://coderwall.com/p/ryzmaa/use-imagemagick-to-create-optimised-and-progressive-jpgs

Then I tried a quick and dirty hack by adding the two options `i.quality` and `i.sharpen` with hard coded values to the code:
``` ruby
        # Scale and crop
        image.combine_options do |i|
          i.quality "75"
          i.sharpen "0x2.5"
          i.resize "#{gen_width}x#{gen_height}^"
          i.gravity "center"
          i.crop "#{gen_width}x#{gen_height}+0+0"
        end
```
It works for me, but a better solution would be to use variables instead, but I don't know how to implement it. 
@robwierzbowski 
Would it be possible to expose these arguments in the config? That would be great.

**Comment by ChrisChinchilla** [comment]
@jsanne @robwierzbowski I think I have a rough idea of how this could be done as the plugin is already pulling in some settings from the config file.

I will have a go at this, but not certain when that will be ;)
