### ISSUE TITLE
Output markup only option

### ISSUE THREAD

**Issue by patrickcate** [rbuchberger/jekyll_picture_tag#34]
It would be nice to have an option to just output the picture markup and skip the image generation. I'm using https://github.com/andismith/grunt-responsive-images to generate other site images, and could easily use it for all images if this option was added.

**Comment by rbuchberger** [comment]
I'm going to close this issue because it's very old, and JPT is pretty strict about image naming which would make it a bit difficult to implement. If this would actually be a useful feature to anyone, please reopen this issue or create a new one!
