### ISSUE TITLE
Issue with animated GIFs

### ISSUE THREAD

**Issue by nhoizey** [rbuchberger/jekyll_picture_tag#49]
I try to use this animated GIF in my content with the picture tag plugin
![the-incredible-machine](https://cloud.githubusercontent.com/assets/78213/3682073/0cb1f4ea-12c4-11e4-844f-7c7e2b758a75.gif)
:

Here is what the resize does:
![the-incredible-machine-300by188-05d3ea](https://cloud.githubusercontent.com/assets/78213/3682092/546d8088-12c4-11e4-8fd7-fce0fa538ac1.gif)

What would you suggest to fix this?

Thanks.

**Comment by rbuchberger** [comment]
I'm going to close this because it's old, hasn't seen activity in years, and people don't really use gifs anymore.
